# Handling Missing Data

## Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([1, 2, True, 2.5])
vals1

array([1. , 2. , 1. , 2.5])

In [ ]:
vals1 = np.array([1, 2, True, 2.5, None])
vals1

array([1, 2, True, 2.5, None], dtype=object)

In [4]:
vals2 = np.array([1, 2,3.5, np.nan])
vals2

array([1. , 2. , 3.5, nan])

In [5]:
1 + np.nan

nan

In [6]:
0 * np.nan

nan

In [ ]:
vals2.sum()

np.float64(nan)

In [8]:
np.nansum(vals2)

np.float64(6.5)

## NaN and None in Pandas

In [9]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [10]:
x = pd.Series(range(5), dtype=int)
x

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [11]:
x[0] = None
x

0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

## Pandas Nullable Dtypes

In [12]:
data = pd.Series([1, np.nan, 2, None, pd.NA])
data

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

In [ ]:
data = pd.Series([1, np.nan, 2, None, pd.NA], dtype='Int32')
data

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

## Operating on Null Values

### isnull
Generates a Boolean mask indicating missing values
### notnull
Opposite of isnull
### dropna
Returns a filtered version of the data
### fillna
Returns a copy of the data with missing values filled or imputed

## Detecting Null Values

In [14]:
data = pd.Series([1, np.nan, "hello", None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [15]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [16]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [17]:
data.dropna()

0        1
2    hello
dtype: object

In [18]:
df = pd.DataFrame([
    [1, 2, np.nan],
    [3, 6, 4],
    [np.nan, 5, 6]
])

df

     0  1    2
0  1.0  2  NaN
1  3.0  6  4.0
2  NaN  5  6.0

In [19]:
df.dropna()

     0  1    2
1  3.0  6  4.0

In [20]:
df.dropna(axis=1)

   1
0  2
1  6
2  5

In [21]:
df2 = pd.DataFrame([
    [1, 2, np.nan],
    [3, np.nan, np.nan],
    [np.nan, 4, np.nan]
])

df2

     0    1   2
0  1.0  2.0 NaN
1  3.0  NaN NaN
2  NaN  4.0 NaN

In [22]:
df2.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [23]:
df2.dropna(axis='columns', how='all')

     0    1
0  1.0  2.0
1  3.0  NaN
2  NaN  4.0

In [24]:
df2.dropna(axis='rows', thresh=2)

     0    1   2
0  1.0  2.0 NaN

## Filling Null Values

In [32]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'), dtype='Int32')
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [33]:
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [34]:
data.fillna(method="ffill")

/tmp/ipython-input-2321864255.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill")

a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [35]:
data.fillna(method='bfill')

/tmp/ipython-input-1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [36]:
df = pd.DataFrame([
    [1, 2, np.nan, np.nan],
    [3, np.nan, 4, np.nan],
    [np.nan, 5, 6, np.nan]
])

df

     0    1    2   3
0  1.0  2.0  NaN NaN
1  3.0  NaN  4.0 NaN
2  NaN  5.0  6.0 NaN

In [37]:
df.fillna(0)

     0    1    2    3
0  1.0  2.0  0.0  0.0
1  3.0  0.0  4.0  0.0
2  0.0  5.0  6.0  0.0

In [40]:
print(df,"\n")

df.fillna(method='ffill')

     0    1    2   3
0  1.0  2.0  NaN NaN
1  3.0  NaN  4.0 NaN
2  NaN  5.0  6.0 NaN

/tmp/ipython-input-2236552387.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     0    1    2   3
0  1.0  2.0  NaN NaN
1  3.0  2.0  4.0 NaN
2  3.0  5.0  6.0 NaN

In [41]:
df.fillna(method='ffill', axis=1)

/tmp/ipython-input-901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)

     0    1    2    3
0  1.0  2.0  2.0  2.0
1  3.0  3.0  4.0  4.0
2  NaN  5.0  6.0  6.0