# Hierarchical Indexing

In [34]:
import pandas as pd
import numpy as np

## Multiply Indexed Series

In [35]:
index = [
    ('California', 2010), 
    ('California', 2020),
    ('New York', 2010), 
    ('New York', 2020),
    ('Texas', 2010), 
    ('Texas', 2020)
    ]

populations = [37253956, 39538223,19378102, 20201249,25145561, 29145505]

pop = pd.Series(populations, index=index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [36]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [37]:
print(pop, "\n")

pop = pop.reindex(index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [38]:
pop[:, 2020]

California    39538223
New York      20201249
Texas         29145505
dtype: int64

## MultiIndex as Extra Dimension

In [39]:
pop_df = pop.unstack()
pop_df

                2010      2020
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [40]:
pop_df.stack()

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [41]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9284094, 8898092,4318033, 4181528,6879014, 7432474]
                       })

pop_df

                    total  under18
California 2010  37253956  9284094
           2020  39538223  8898092
New York   2010  19378102  4318033
           2020  20201249  4181528
Texas      2010  25145561  6879014
           2020  29145505  7432474

In [42]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

                2010      2020
California  0.249211  0.225050
New York    0.222831  0.206994
Texas       0.273568  0.255013

## Methods of MultiIndex Creation

In [43]:
df = pd.DataFrame(np.random.rand(4, 2),index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],columns=['data1', 'data2'])

df

        data1     data2
a 1  0.599583  0.086177
  2  0.948823  0.604453
b 1  0.196180  0.132305
  2  0.206954  0.742875

In [44]:
data = {('California', 2010): 37253956,
        ('California', 2020): 39538223,
        ('New York', 2010): 19378102,
        ('New York', 2020): 20201249,
        ('Texas', 2010): 25145561,
        ('Texas', 2020): 29145505}

pd.Series(data)

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [45]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [46]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [47]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [48]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

## MultiIndex Level Names

In [49]:
pop.index.names = ['state', 'year']
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

## MultiIndex for Columns

In [50]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'],['HR', 'Temp']],names=['subject', 'type'])

In [51]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[ 0.1, -0.5, -0.2, -1.2,  0.7,  1. ],
       [ 0.6, -0.9,  0. ,  0.7, -0.2, -1.2],
       [-0.1,  0.8,  0.2, -1. ,  1.7, -0.9],
       [-1.9, -0.7, -1.4, -0. ,  0.2, -0.4]])

In [52]:
data[:, ::2] *= 10
data += 37
data

array([[38. , 36.5, 35. , 35.8, 44. , 38. ],
       [43. , 36.1, 37. , 37.7, 35. , 35.8],
       [36. , 37.8, 39. , 36. , 54. , 36.1],
       [18. , 36.3, 23. , 37. , 39. , 36.6]])

In [53]:
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      38.0  36.5  35.0  35.8  44.0  38.0
     2      43.0  36.1  37.0  37.7  35.0  35.8
2014 1      36.0  37.8  39.0  36.0  54.0  36.1
     2      18.0  36.3  23.0  37.0  39.0  36.6

## Indexing and Slicing a MultiIndex

In [56]:
pop['California']

year
2010    37253956
2020    39538223
dtype: int64

In [57]:
pop['California', 2010]

np.int64(37253956)

In [58]:
pop["California" : "New York"]

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
dtype: int64

In [59]:
pop[pop > 20200000]

state       year
California  2010    37253956
            2020    39538223
New York    2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [60]:
pop[["California", "Texas"]]

state       year
California  2010    37253956
            2020    39538223
Texas       2010    25145561
            2020    29145505
dtype: int64

In [61]:
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      38.0  36.5  35.0  35.8  44.0  38.0
     2      43.0  36.1  37.0  37.7  35.0  35.8
2014 1      36.0  37.8  39.0  36.0  54.0  36.1
     2      18.0  36.3  23.0  37.0  39.0  36.6

In [62]:
health_data["Guido", "HR"]

year  visit
2013  1        35.0
      2        37.0
2014  1        39.0
      2        23.0
Name: (Guido, HR), dtype: float64

In [63]:
health_data.iloc[:2, :2]

subject      Bob
type          HR  Temp
year visit
2013 1      38.0  36.5
     2      43.0  36.1