# Introducing pandas objects.

In [2]:
import pandas as pd
import numpy as np
pd.__version__

'2.3.2'

In [3]:
# Series object 
data=pd.Series([10,20,30,40,50])
print(data)

# for i,j in enumerate(data):
#     print(i," ",j)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
data.values

array([10, 20, 30, 40, 50])

In [5]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
data[0]

np.int64(10)

In [7]:
data[1:4]

1    20
2    30
3    40
dtype: int64

In [9]:
data2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [10]:
data2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
data2['c']

np.int64(3)

In [12]:
data2['a':'d']

a    1
b    2
c    3
d    4
dtype: int64

In [16]:
population_dict={
    'hassan':'1.2M',
    'bengaluru':'12M',
    'mosore':'5M',
    'kodagu':'3M'
}

population=pd.Series(population_dict)

In [17]:
population

hassan       1.2M
bengaluru     12M
mosore         5M
kodagu         3M
dtype: object

In [18]:
population['hassan']

'1.2M'

In [19]:
population['hassan':'kodagu']

hassan       1.2M
bengaluru     12M
mosore         5M
kodagu         3M
dtype: object

103

In [13]:
# series object construction
pd.Series(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [14]:
index=['a','b','c','d','e']
pd.Series(data,index=index)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [15]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [16]:
pd.Series(4,index=[1,2,3,4,5])

1    4
2    4
3    4
4    4
5    4
dtype: int64

In [17]:
pd.Series({2:'hello',1:'world'})

2    hello
1    world
dtype: object

In [18]:
pd.Series({2:'hello',1:'world'},index=[1,2])

1    world
2    hello
dtype: object

In [19]:
# dataframe object
city=pd.Series(['mumbai','chennai','kolkatta'])
population=['10M','15M','5M']

cities=pd.DataFrame({'city':city,'population':population})
cities

       city population
0    mumbai        10M
1   chennai        15M
2  kolkatta         5M

In [20]:
cities.index

RangeIndex(start=0, stop=3, step=1)

In [21]:
cities.columns

Index(['city', 'population'], dtype='object')

In [22]:
cities['city']

0      mumbai
1     chennai
2    kolkatta
Name: city, dtype: object

In [23]:
data=[{'a':i,'b':2*i} for i in range(5)]

In [24]:
data

[{'a': 0, 'b': 0},
 {'a': 1, 'b': 2},
 {'a': 2, 'b': 4},
 {'a': 3, 'b': 6},
 {'a': 4, 'b': 8}]

In [25]:
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8

In [26]:
data=[{'a':1,'b':2},{'b':3,'c':4}]
data

[{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]

In [27]:
pd.DataFrame(data)

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [29]:
pd.DataFrame(np.random.rand(3,2),
             columns=['col1','col2'],
             index=['a','b','c'])

       col1      col2
a  0.172672  0.415432
b  0.020311  0.124105
c  0.744719  0.068574

In [30]:
arr=np.zeros(3,dtype=[('a','i4'),('b','i8'),('c','f8')])
arr

array([(0, 0, 0.), (0, 0, 0.), (0, 0, 0.)],
      dtype=[('a', '<i4'), ('b', '<i8'), ('c', '<f8')])

In [43]:
pd.DataFrame(arr)

   a  b    c
0  0  0  0.0
1  0  0  0.0
2  0  0  0.0

In [31]:
pd.Index([1,2,3,4,5])[1:4]

Index([2, 3, 4], dtype='int64')

In [7]:
data=pd.Index([1,2,3,4,5])
data[0]=5

TypeError: Index does not support mutable operations

In [3]:
idx=pd.Index([1,2,3,4,5])
idx2=pd.Index([4,5,6,7,8,9])

In [4]:
idx.intersection(idx2)

Index([4, 5], dtype='int64')

In [5]:
idx.union(idx2)

Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [6]:
idx.difference(idx2)

Index([1, 2, 3], dtype='int64')