# Operating on Data in Pandas

In [16]:
import numpy as np
import pandas as pd

In [17]:
rng=np.random.default_rng(30)
ser=pd.Series(rng.integers(0,10,4))
ser

0    1
1    2
2    7
3    4
dtype: int64

In [18]:
df=pd.DataFrame(rng.integers(0,10,(3,4)),columns=['a','b','c','d'])
df

   a  b  c  d
0  3  0  6  5
1  2  7  1  8
2  0  3  7  1

In [19]:
np.exp(ser)

0       2.718282
1       7.389056
2    1096.633158
3      54.598150
dtype: float64

In [20]:
ser

0    1
1    2
2    7
3    4
dtype: int64

In [21]:
np.sin(df*np.pi /4)

          a         b         c             d
0  0.707107  0.000000 -1.000000 -7.071068e-01
1  1.000000 -0.707107  0.707107 -2.449294e-16
2  0.000000  0.707107 -0.707107  7.071068e-01

In [22]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505,
 'Florida': 21538187}, name='population')

print(population,'\n')
print(area,'\n')
print(population / area)

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [23]:
area.index

Index(['Alaska', 'Texas', 'California'], dtype='object')

In [24]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

In [25]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

print(A,'\n')
print(B)
A + B

0    2
1    4
2    6
dtype: int64

1    1
2    3
3    5
dtype: int64

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [26]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [37]:
A = pd.DataFrame(rng.integers(0,20,(2,3)), columns=['a','b','c'])
A

   a   b   c
0  6  13   5
1  0   2  10

In [40]:
B = pd.DataFrame(rng.integers(0,20,(3,4)),columns=['a','b','c','d'])
B

    a   b   c   d
0   2  12  16  13
1  13   5  17   3
2   4  19   8   5

In [41]:
A + B

      a     b     c   d
0   8.0  25.0  21.0 NaN
1  13.0   7.0  27.0 NaN
2   NaN   NaN   NaN NaN

In [43]:
A.add(B)

      a     b     c   d
0   8.0  25.0  21.0 NaN
1  13.0   7.0  27.0 NaN
2   NaN   NaN   NaN NaN

In [44]:
A.add(B, fill_value=A.values.mean())

      a     b     c     d
0   8.0  25.0  21.0  19.0
1  13.0   7.0  27.0   9.0
2  10.0  25.0  14.0  11.0