In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('cardekho_imputated.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Feature Engineering

In [4]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [6]:
df.drop(['car_name', 'brand'], inplace=True, axis=1)

In [7]:
df.head()

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [8]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [9]:
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
cat_features

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [10]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
num_features

['Unnamed: 0',
 'vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [11]:
descrete_features = [feature for feature in df.columns if len(df[feature].unique()) <= 25]
descrete_features

['vehicle_age', 'seller_type', 'fuel_type', 'transmission_type', 'seats']

In [12]:
continueous_features = [feature for feature in df.columns if feature not in descrete_features]
continueous_features

['Unnamed: 0',
 'model',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'selling_price']

In [13]:
df.drop('Unnamed: 0', inplace=True, axis=1)

In [14]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [15]:
X = df.drop('selling_price', axis=1)
y = df.selling_price

In [16]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

X['model'] = encoder.fit_transform(X['model'])

In [28]:
num_features = (df.select_dtypes(exclude='object').columns)[:-1]
num_features

Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats'], dtype='object')

In [29]:
cat_features = (df.select_dtypes(include='object').columns)[1:]
cat_features

Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='object')

In [30]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [31]:
scaler = StandardScaler()
oh_encoder = OneHotEncoder()

transformer = ColumnTransformer(
  [
    ('OneHotEncoder', oh_encoder, cat_features),
    ('StandardScaler', scaler, num_features)
  ], remainder='passthrough'
)

In [32]:
X = transformer.fit_transform(X)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor

In [43]:
from sklearn.metrics import r2_score, mean_absolute_error

In [44]:
def evaluate(actual, pred):
  return r2_score(actual, pred), mean_absolute_error(actual, pred)

In [45]:
models = {
  "LinearRegression" : LinearRegression(),
  "Lasso" : Lasso(), 
  "Ridge" : Ridge(),
  "RandomForestRegressor" : RandomForestRegressor(),
  "DecisionTreeRegressor" : DecisionTreeRegressor()
}

In [46]:
for key, val in models.items():

  print("\n\n\n-------------------------------------")
  print(f"Prediction for {key}")

  model = val
  model.fit(x_train, y_train)

  y_pred = model.predict(x_test)

  score, error = evaluate(y_test, y_pred)

  print(f"R2 Score: {score}")
  print(f"mean_absolute_error: {error}")

-------------------------------------
Prediction for LinearRegression
R2 Score: 0.6645109298852045
mean_absolute_error: 279618.579415833



-------------------------------------
Prediction for Lasso
R2 Score: 0.664512147349274
mean_absolute_error: 279615.00641396095



-------------------------------------
Prediction for Ridge
R2 Score: 0.6645244931091975
mean_absolute_error: 279558.25354907



-------------------------------------
Prediction for RandomForestRegressor
R2 Score: 0.9294427173270255
mean_absolute_error: 102185.99256315458



-------------------------------------
Prediction for DecisionTreeRegressor
R2 Score: 0.8814647671402837
mean_absolute_error: 123025.5892528922